version: '3.6'

services:
  db-pgsql:
    image: postgres:latest
    hostname: pgsql
    volumes:
      - ./db-pgsql:/var/lib/postgresql/data
      - ./db-archive:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_DB=db_datascience
      - POSTGRES_USER=datascience
      - POSTGRES_PASSWORD=datascience
      - POSTGRES_INITDB_ARGS='--data-checksums'
    networks:
      - datascience-net
    deploy:
      mode: replicated
      replicas: 2
      endpoint_mode: dnsrr
      restart_policy:
        condition: on-failure

  adminer:
    image: adminer:latest
    hostname: adminer
    environment:
      - ADMINER_DESIGN=lucas-sandery
    ports:
      - '9010:8080'
    networks:
      - datascience-net
    depends_on:
      - db-pgsql
    deploy:
      restart_policy:
        condition: on-failure

  app:
    image: gworkx/datascience:python
    hostname: python
    volumes:
     - ./app-code:/app
    environment:
     - DB_HOST=db-pgsql
     - DB_NAME=POSTGRES_DB
     - DB_PASSWORD=POSTGRES_PASSWORD
    entrypoint: /app/app.py
    ports:
      - '5010:5000'
    networks:
      - datascience-net
    depends_on:
      - db-pgsql
    deploy:
      restart_policy:
        condition: on-failure

  jupyter:
    image: gworkx/datascience:jupyter
    hostname: jupyter
    volumes:
     - ./jupyter-notebook-conf:/home/jovyan/.jupyter
    environment:
     - DB_HOST=db-pgsql
     - DB_NAME=POSTGRES_DB
     - DB_PASSWORD=POSTGRES_PASSWORD
    ports:
      - '5011:8888'
    networks:
      - datascience-net
    depends_on:
      - db-pgsql
    deploy:
      restart_policy:
        condition: on-failure

networks:
  datascience-net:
    driver: overlay
